/**
 * Database Initialization and Helper Utilities
 * Uses JSON file-based storage for vector data and session histories.
 * This file-based system provides structured, type-safe operations for RAG search.
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const DATA_DIR = process.env.DB_PATH
  ? path.dirname(path.resolve(process.env.DB_PATH))
  : path.join(__dirname, '..', '..', 'data');

const DB_FILE = path.join(DATA_DIR, 'database.json');

// ==================== JSDoc Type Definitions ====================

/**
 * @typedef {Object} KnowledgeChunk
 * @property {string} id - Unique identifier for the chunk (auto-generated if not provided)
 * @property {string} division - Service division identifier (e.g. 'printer', 'cctv', 'windows', 'lan', etc.)
 * @property {string} title - Title of the document chunk
 * @property {string} content - Markdown text content of the SOP troubleshooting steps
 * @property {'ringan'|'berat'} category - Classification of the issue severity ('ringan' or 'berat')
 * @property {number[]} embedding - Vector embedding values generated by Ollama for semantic search
 * @property {Object} metadata - Metadata regarding the source of the chunk
 * @property {string} metadata.sourceFile - Original markdown filename
 * @property {number} metadata.chunkIndex - Position index of the chunk in the file
 * @property {number} metadata.totalChunks - Total chunks extracted from the file
 * @property {string} createdAt - Timestamp when the chunk was created (ISO 8601 format)
 */

/**
 * @typedef {Object} ChatSession
 * @property {string} id - Unique session UUID
 * @property {string|null} selectedDivision - Currently selected division for troubleshooting
 * @property {'active'|'resolved'|'escalated'} status - Current status of the chat session
 * @property {string} createdAt - Timestamp when the session was created (ISO 8601 format)
 * @property {string} updatedAt - Timestamp when the session was last updated (ISO 8601 format)
 */

/**
 * @typedef {Object} ChatMessage
 * @property {string} id - Unique message identifier
 * @property {string} sessionId - UUID of the associated chat session
 * @property {'user'|'assistant'|'system'} role - Role of the message author ('user' | 'assistant' | 'system')
 * @property {string} content - Content text of the chat message (supports markdown)
 * @property {string} createdAt - Timestamp when the message was sent (ISO 8601 format)
 */

/**
 * @typedef {Object} DatabaseSchema
 * @property {KnowledgeChunk[]} knowledgeChunks - List of ingested knowledge chunks
 * @property {ChatSession[]} chatSessions - Active and archived chat sessions
 * @property {ChatMessage[]} chatMessages - All message logs associated with chat sessions
 */

// ==================== In-Memory Database State ====================

/**
 * In-memory database cache
 * @type {DatabaseSchema}
 */
let db = {
  knowledgeChunks: [],
  chatSessions: [],
  chatMessages: []
};

/**
 * Initialize the database - ensure data directory exists and load existing JSON database.
 * @returns {Promise<DatabaseSchema>} Resolves to the loaded database schema
 */
export async function initDatabase() {
  // Ensure data directory exists
  if (!fs.existsSync(DATA_DIR)) {
    fs.mkdirSync(DATA_DIR, { recursive: true });
  }

  // Load existing data if available
  if (fs.existsSync(DB_FILE)) {
    try {
      const raw = fs.readFileSync(DB_FILE, 'utf-8');
      db = JSON.parse(raw);
      console.log(`📦 Loaded ${db.knowledgeChunks.length} knowledge chunks, ${db.chatSessions.length} sessions`);
    } catch (e) {
      console.warn('⚠️ Could not parse existing database, starting fresh');
      db = { knowledgeChunks: [], chatSessions: [], chatMessages: [] };
    }
  }

  return db;
}

/**
 * Persist the current in-memory database cache to disk as JSON.
 * @returns {void}
 */
export function saveDatabase() {
  fs.writeFileSync(DB_FILE, JSON.stringify(db, null, 2), 'utf-8');
}

/**
 * Retrieve the raw database instance in memory.
 * @returns {DatabaseSchema} The active in-memory database object
 */
export function getDatabase() {
  return db;
}

// ==================== Knowledge Chunks CRUD ====================

/**
 * Add a new knowledge chunk to the database and persist to disk.
 * @param {Omit<KnowledgeChunk, 'id'|'createdAt'> & {id?: string, createdAt?: string}} chunk - The chunk data
 * @returns {void}
 */
export function addKnowledgeChunk(chunk) {
  db.knowledgeChunks.push({
    id: chunk.id || Date.now().toString(36) + Math.random().toString(36).substr(2, 5),
    division: chunk.division,
    title: chunk.title || '',
    content: chunk.content,
    category: chunk.category || 'ringan',
    embedding: chunk.embedding || [],
    metadata: chunk.metadata || {},
    createdAt: new Date().toISOString()
  });
  saveDatabase();
}

/**
 * Get all knowledge chunks belonging to a specific division.
 * @param {string} division - The division identifier (e.g. 'cctv')
 * @returns {KnowledgeChunk[]} List of chunks matching the division
 */
export function getChunksByDivision(division) {
  return db.knowledgeChunks.filter(c => c.division === division);
}

/**
 * Retrieve all knowledge chunks stored in the database.
 * @returns {KnowledgeChunk[]} List of all chunks
 */
export function getAllChunks() {
  return db.knowledgeChunks;
}

/**
 * Clear knowledge chunks from the database.
 * @param {string|null} [division=null] - Division to clear, or null to clear all chunks
 * @returns {void}
 */
export function clearChunks(division = null) {
  if (division) {
    db.knowledgeChunks = db.knowledgeChunks.filter(c => c.division !== division);
  } else {
    db.knowledgeChunks = [];
  }
  saveDatabase();
}

// ==================== Chat Sessions CRUD ====================

/**
 * Create a new chat session.
 * @param {string} sessionId - The unique session UUID
 * @returns {ChatSession} The created chat session object
 */
export function createChatSession(sessionId) {
  const session = {
    id: sessionId,
    // Data pelapor (diisi lewat formulir pendataan sebelum memilih divisi)
    reporter: null, // { nama, fungsi, lokasi }
    selectedDivision: null,
    status: 'active', // active | resolved | escalated
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  };
  db.chatSessions.push(session);
  saveDatabase();
  return session;
}

/**
 * Find a chat session by its unique ID.
 * @param {string} sessionId - The session UUID
 * @returns {ChatSession|undefined} The session object if found, otherwise undefined
 */
export function getChatSession(sessionId) {
  return db.chatSessions.find(s => s.id === sessionId);
}

/**
 * Update chat session attributes.
 * @param {string} sessionId - The session UUID
 * @param {Partial<ChatSession>} updates - Object containing fields to update
 * @returns {ChatSession|undefined} The updated session object if found, otherwise undefined
 */
export function updateChatSession(sessionId, updates) {
  const session = db.chatSessions.find(s => s.id === sessionId);
  if (session) {
    Object.assign(session, updates, { updatedAt: new Date().toISOString() });
    saveDatabase();
  }
  return session;
}

// ==================== Chat Messages CRUD ====================

/**
 * Add a new chat message to a session history and persist.
 * @param {string} sessionId - UUID of the session
 * @param {'user'|'assistant'|'system'} role - The sender role
 * @param {string} content - Message text content
 * @returns {ChatMessage} The created message object
 */
export function addChatMessage(sessionId, role, content) {
  const message = {
    id: Date.now().toString(36) + Math.random().toString(36).substr(2, 5),
    sessionId,
    role, // 'user' | 'assistant' | 'system'
    content,
    createdAt: new Date().toISOString()
  };
  db.chatMessages.push(message);
  saveDatabase();
  return message;
}

/**
 * Get all chat messages associated with a session, sorted by creation date.
 * @param {string} sessionId - UUID of the session
 * @returns {ChatMessage[]} Chronologically ordered messages
 */
export function getChatMessages(sessionId) {
  return db.chatMessages
    .filter(m => m.sessionId === sessionId)
    .sort((a, b) => new Date(a.createdAt) - new Date(b.createdAt));
}
